<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ParrotAgent.NUI</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<!-- dotnet run 时工作目录设为项目目录，使 .parrotcode.yaml 能被三级发现命中 -->
	<RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParrotAgent-Kenel\ParrotAgent-Kenel.csproj" />
    <ProjectReference Include="..\ParrotAgent-Log\ParrotAgent-Log.csproj" />
    <ProjectReference Include="..\ParrotAgent-OpenAI\ParrotAgent-OpenAI.csproj" />
    <ProjectReference Include="..\ParrotAgent-Tool\ParrotAgent-Tool.csproj" />
  </ItemGroup>

</Project>
