<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ParrotAgent.Kenel</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src\sinker\**" />
    <EmbeddedResource Remove="src\sinker\**" />
    <None Remove="src\sinker\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.ServerSentEvents" Version="10.0.11" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
