<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ParrotAgent.Command</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\bin\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParrotAgent-Kernel\ParrotAgent-Kernel.csproj" />
  </ItemGroup>

</Project>
